### PR TITLE
feat: readme

### PR DESCRIPTION
**Pull request by Miqhtiedev**
Create a readme file

### CODE REVIEW

**Comment by Miqhtiedev** [comment]
Once we have an avatar for this bot it should be added to the readme

**Comment by ryanArora** [comment]
suggestion: add shields right under the title
https://shields.io/

e.g
code-style prettier
license
latest commit

**Review by Averyyyyyyyy — APPROVED** [review]

**Comment by Miqhtiedev** [comment]
Added readme badges, should be noted that the LICENSE badge won't function (will show as "not specified") until we add a license

**Review by Averyyyyyyyy — APPROVED** [review]

**Review by Averyyyyyyyy — APPROVED** [review]
I like this one

**Review by ryanArora — APPROVED** [review]
Changed style, removed spacing between shields and moved description under.

Looks good to me

**Pull request merged**
